pipeline {
    agent any
    tools {
        nodejs 'NodeJS'   // Must match the name you configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/02250376cst-cmd/Tshering-Tenzin_02250376_DSO101.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install') {
            steps {
                bat 'npm install'
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Test') {
            steps {
                bat 'npm test'
            }
            post {
                always {
                    junit 'junit.xml'
                }
            }
        }
    }
}
