services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: <dpg-d70juk6a2pns73b6mjdg-a>
      - key: DB_USER
        value: <tshering_tenzin_user>
      - key: DB_PASSWORD
        value: <QoW70BIgpkb7AK3SD7GpH2Y4y33HTXLn>
      - key: PORT
        value: 5432

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com